name: build and test npm package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true
      github_token:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
      GITHUB_TOKEN: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit

      - name: "validate package version"
        run: |
          echo "PACKAGE_VERSION=v$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
          gh release list ${{ env.PACKAGE_VERSION }}
          exit code !$?
