name: build and test npm package

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
    secrets:
      npm-token:
        required: true
      github-token:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm-token }}
      GITHUB_TOKEN: ${{ secrets.github-token }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit

      - name: "validate package version"
        run: |
          export PACKAGE_VERSION=v$(node -p -e "require('./package.json').version")
          set +e
          gh release view $PACKAGE_VERSION
          export EXIT_CODE=$?
          set -e
          if [ $EXIT_CODE -eq 0 ]; then
            echo "$PACKAGE_VERSION already exists"
            exit 1
          fi

