name: build and test npm package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true
      github_token:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
      GITHUB_TOKEN: ${{ secrets.github_token }}
      PACKAGE_VERSION_EXISTS: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit

      - name: "check if package version exists"
        continue-on-error: true
        run: |
          echo "PACKAGE_VERSION=v$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
          gh release view ${{ env.PACKAGE_VERSION }}
          echo "PACKAGE_VERSION_EXISTS=1" >> $GITHUB_ENV

      - name: "validate package version"
        run: |
          if [ ${{ env.PACKAGE_VERSION_EXISTS }} -eq 1 ]; then
            echo "${{ env.PACKAGE_VERSION }} already exists"
            exit 1
          else
            exit 0
          fi

