name: publish npm package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true
      github_token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
      GITHUB_TOKEN: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: set version environment variable
        run: |
          echo "PACKAGE_VERSION=v$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - run: yarn publish

      - name: "Create new release"
        run: gh release create ${{ env.PACKAGE_VERSION }} --notes ""