name: build-test-and-package

on:
  workflow_call:
    inputs:
      run-integration-tests:
        description: "flag to run `yarn test:int` command"
        default: false
        required: false
        type: boolean
      node-version:
          type: string
          required: false
          default: "lts/gallium"
    secrets:
      npm-token:
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm-token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: yarn format
      - run: yarn lint
      - run: yarn test:unit
      - name: integration tests
        run: yarn test:int
        if: ${{ inputs.run-integration-tests }}
      - name: "remove dev dependencies"
        run: yarn install --production
      - name: "build artifact"
        run: zip -r build.zip build node_modules
      - name: "upload artifact to github"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip
