name: build-and-test-package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit
      - name: "remove dev dependencies"
        run: yarn install --production

      - name: "build artifact"
        run: zip -r build.zip build package.json

      - name: "upload artifact to github"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip
