name: build-and-test

on:
  workflow_call:
    inputs:
      run-integration-tests:
        description: "flag to run `yarn test:int` command"
        default: false
        required: false
        type: boolean
      working-directory:
        type: string
        required: false
        default: .
      node-version:
        type: string
        required: false
        default: "lts/gallium"
    secrets:
      npm-token:
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm-token }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
          cache-dependency-path: "${{ inputs.working-directory }}/yarn.lock"
      - run: yarn install
      - run: yarn build
      - run: yarn format
      - run: yarn lint
      - run: yarn test:unit
      - name: integration tests
        run: yarn test:int
        if: ${{ inputs.run-integration-tests }}
      