name: build-and-test

on:
  workflow_call:
    secrets:
      npm_token:
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test:unit
      