name: build-and-test

on:
  workflow_call:
    inputs:
      run-integration-tests:
        description: "flag to run `yarn test:int` command"
        default: false
        required: false
        type: boolean
      working-directory:
        type: string
        required: false
        default: ./
      override-integration-test-command:
        description: "override the default integration test command"
        required: false
        type: string
    secrets:
      npm-token:
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm-token }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test:unit
      - name: integration tests
        run: ${{ inputs.override-integration-test-command || 'yarn test:int' }}
        if: ${{ inputs.run-integration-tests }}
      