name: build-and-test-package

on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - uses: ./.github/actions/typescript-build-and-test

      - name: "Check for available package version"
        run: |
          echo "PACKAGE_VERSION=v$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
          git ls-remote --tags origin ${{env.PACKAGE_VERSION}}

      - name: "build artifact"
        run: zip -r build.zip build package.json

      - name: "upload artifact to github"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip
