name: build-and-test-package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit
